name: Update flake inputs

on:
  workflow_dispatch:
  push:
    paths:
    - '**'

env:
  CACHIX_USER: gfanton
  UPDATE_BRANCH: flake-update

jobs:
  update-flake-inputs:
    name: Update Flake inputs
    runs-on: ubuntu-latest
    env:
      CONFIG_NAME: githubCI
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Nix
      uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: ${{ env.CACHIX_USER }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build and switch to home-manager env
      run: |


        # Prevent conflict between Cachix installed by workflow and the one installed in the config
        nix-env --set-flag priority 1 cachix

        # Build and switch to home-manager env
        nix build ".#homeConfigurations.$CONFIG_NAME.activationPackage"
        ./result/activate switch --verbose 
        nixos_old_gen=$(readlink -f $HOME/.nix-profile) || true
        echo current generation: $nixos_old_gen"
        
        # ls /nix/var/nix/profiles || true
        # ls /nix/var/nix/profiles/per-user/root || true

        # readlink -f /nix/var/nix/profiles/per-user/root/home-manager || true
        # readlink -f $HOME/.nix-profile || true


        # update all inputs by recreating the flake
        nix build --recreate-lock-file ".#homeConfigurations.$CONFIG_NAME.activationPackage"
        ./result/activate switch --verbose
        nixos_new_gen=$(readlink -f $HOME/.nix-profile)
        echo "new generation: $nixos_new_gen"

        # ls /nix/var/nix/profiles || true
        # ls /nix/var/nix/profiles/per-user/root || true
 
        # readlink -f /nix/var/nix/profiles/per-user/root/profile || true
        # readlink -f $HOME/.nix-profile || true


        # generate diff
        nix-shell -p nvd --run "nvd diff $nixos_old_gen $nixos_new_gen"

        



